parameters:
  party:
    start: '2020-01-10 15:00'
    end: '2020-01-10 17:00'
  workers:
    - id: 1
      vacations:
        - start: '01-11'
          end: '01-25'
        - start: '02-01'
          end: '02-15'
      working_hours:
        - start: '10:00'
          end: '13:00'
        - start: '14:00'
          end: '19:00'
    - id: 2
      vacations:
        - start: '02-01'
          end: '03-01'
      working_hours:
        - start: '9:00'
          end: '12:00'
        - start: '13:00'
          end: '18:00'
